spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  sql:
    init:
      mode: never

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  bot-username: ${TELEGRAM_BOT_USERNAME}
  webhook-secret: ${TELEGRAM_WEBHOOK_SECRET}